### ISSUE TITLE
demo.py fails

### ISSUE THREAD

**Issue by zanaviska** [yhenon/pyimgsaliency#9]
pip version: 20.3.3
python version: 3.7.9

step to reproduce:
```
git clone https://github.com/yhenon/pyimgsaliency
cd pyimgsaliency
python setup.py install
cd pyimgsaliency
python demo.py
```

get the following error
```
C:\Users\avh\AppData\Local\Programs\Python\Python37\lib\site-packages\pyimgsaliency-0.1-py3.7.egg\pyimgsaliency\saliency.py:83: FutureWarning: skimage.measure.label's indexing starts from 0. In future version it will start from 1. To disable this warning, explicitely set the `start_label` parameter to 1.
  segments_slic = slic(img_rgb, n_segments=250, compactness=10, sigma=1, enforce_connectivity=False)
Traceback (most recent call last):
  File ".\demo.py", line 8, in <module>
    rbd = psal.get_saliency_rbd(filename).astype('uint8')
  File "C:\Users\avh\AppData\Local\Programs\Python\Python37\lib\site-packages\pyimgsaliency-0.1-py3.7.egg\pyimgsaliency\saliency.py", line 92, in get_saliency_rbd
    (vertices,edges) = make_graph(grid)
  File "C:\Users\avh\AppData\Local\Programs\Python\Python37\lib\site-packages\pyimgsaliency-0.1-py3.7.egg\pyimgsaliency\saliency.py", line 62, in make_graph
    vertices[x/num_vertices]] for x in edges]
  File "C:\Users\avh\AppData\Local\Programs\Python\Python37\lib\site-packages\pyimgsaliency-0.1-py3.7.egg\pyimgsaliency\saliency.py", line 62, in <listcomp>
    vertices[x/num_vertices]] for x in edges]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

**Comment by zanaviska** [comment]
okay, I figured it out
codebase is written for python2, and I have installed python3
so in 62 insaliency.py you have to replace / with //
and replace every xrange with range
